---
title: "Querying the DHS API in R"
author: "Tobias Holden"
date: "7/19/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(jsonlite)
library(tidyverse)
```


```{r}
# Abbreviated country code, check list here:
# https://dhsprogram.com/data/File-Types-and-Names.cfm#CP_JUMP_10136

countryIds=c('BF') # countryIDs in quotes, separated by commas if multiple

# Level of stratification ('national' or 'subnational')

breakdown=c('subnational')

# Indicator(s) of interest. For a full list of 3,785 DHS indicators, look here:
# https://api.dhsprogram.com/rest/dhs/indicators?returnFields=IndicatorId,Label,Definition&f=html
#  
# Example malaria indicators:
# - CH_FEVR_C_FEV = % of children U5 (or U3) with fever in the 2 weeks preceding the survey
# - ML_FEVT_C_ADV	= % of children U5 with recent (<2wk) fever for whom advice/treatment was sought
# - ML_NETP_H_ITN = % of households with at least 1 ITN
# - ML_IRSM_H_IRS = % of households with IRS in the last 12 months
# - ML_PMAL_C_RDT = Malaria prevalence among children age 6-59 months tested by RDT 
# - ML_PMAL_C_RDL = Lower limit of 95% CI for ML_PMAL_C_RDT
# - ML_PMAL_C_RDU = Upper limit of 95% CI for ML_PMAL_C_RDT
#
# Note: some indicators may not apply to all countries/districts/surveys

indicatorIds=c('ML_IRSM_H_IRS','ML_NETP_H_ITN','ML_FEVT_C_ADV','ML_PMAL_C_RDT', 'ML_PMAL_C_RDL', 'ML_PMAL_C_RDU')

```

```{r}
#### Build API Query ####

base_url <- "http://api.dhsprogram.com/rest/dhs/data?f=json&surveyid=all"
end_url <- "&lang=en&f=json"
url <- paste(base_url,
             "&countryIds=",paste(countryIds,collapse=','),
             "&breakdown=",breakdown,
             "&indicatorIds=",paste(indicatorIds,collapse=','),
             end_url,
             sep = '')
url <- (url)


#### Call API ####

dhs_data <- fromJSON(url) # get page
dhs_data <- dhs_data$Data # save dataframe


#### Plot Results ###

# Trends in intervention indicators by country-region 
dhs_data %>% 
  filter(!IndicatorId %in% c('ML_PMAL_C_RDT', 'ML_PMAL_C_RDL', 'ML_PMAL_C_RDU')) %>%
  ggplot(aes(x=SurveyYear, y=Value, color = Indicator)) +
  geom_line(size=1) +
  geom_point(size=2, shape=21, fill="white") +
  facet_wrap(~paste(CountryName,CharacteristicLabel,sep='-'), ncol=5) +
  theme_minimal() +
  theme(legend.position="bottom",
        legend.justification = c(0,0),
        axis.text.x=element_text(angle=90, vjust=0.5),
        panel.grid.minor.x = element_blank()) +
  scale_x_continuous(breaks=seq(2000,2020,1)) +
  guides(color=guide_legend(direction = "vertical")) +
  labs(color=NULL)

# RDT Prevalence trends by country-region (where available)
dhs_data %>% 
  filter(IndicatorId %in% c('ML_PMAL_C_RDT', 'ML_PMAL_C_RDL', 'ML_PMAL_C_RDU')) %>%
  ggplot(aes(x=SurveyYear, y=Value)) +
  geom_line(aes(group=SurveyYear)) +
  geom_line(data=dhs_data[dhs_data$IndicatorId=="ML_PMAL_C_RDT",],
            size=1) +
  geom_point(size=2, shape=21, fill="white") +
  facet_wrap(~paste(CountryName,CharacteristicLabel,sep='-'), ncol=5) +
  theme_minimal() +
  theme(legend.position="bottom",
        legend.justification = c(0,0),
        axis.text.x=element_text(angle=90, vjust=0.5),
        panel.grid.minor.x = element_blank()) +
  scale_x_continuous(breaks=seq(2000,2025,1)) +
  guides(color=guide_legend(direction = "vertical")) +
  labs(color=NULL) 
```